# meta-embedded/conf/layer.conf
# Configuration for meta-embedded custom layer

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "embedded"
BBFILE_PATTERN_embedded = "^${LAYERDIR}/"
BBFILE_PRIORITY_embedded = "10"

LAYERSERIES_COMPAT_embedded = "scarthgap"
